# Use an official MariaDB image as the base image
FROM mariadb:latest

# Set the working directory
WORKDIR /app

# Copy the database initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose port 3306 for MariaDB
EXPOSE 3306
