version: '3.8'

services:
  server:
    container_name: springboot-container
    build: .
    restart: always
    image: image-java  # Replace with your actual image name
    ports:
      - "8080:8080"
    environment:
      # Spring Boot environment variables (replace with your actual values)
      SPRING_DATASOURCE_URL: jdbc:mariadb://127.0.0.1:3306/studentmanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver


